title: test title
description: test descr.
show_downloads: False
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
github:
  zip_url: http://example.com/download.zip
  tar_url: http://example.com/download.zip
  github_url: http://example.com/github