title: "SCP:FC Beta Wiki"
author: "RAVFEN"

navbar-links:
  About Me: "https://github.com/raven-sgwc"
  Resources:
    - The Game: "https://play.google.com/store/apps/details?id=com.IntelligentCat.com.unity.SCPCards&hl=en_US"
    - Release Wiki: "https://scp-fc.fandom.com/wiki/SCP:_Foundation_Chronicles_Wiki"
  Author's home: "https://ptb.discord.com/invite/9Nu2KNWSwn"

avatar: "https://raven-sgwc.github.io/SCP-FC/assets/images/BETA_WIKI.png"

title-img: "https://raven-sgwc.github.io/SCP-FC/assets/images/BETA_WIKI.png"

round-avatar: true

social-network-links:
  email: "someone@example.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: example1
  github: example2
  twitter: example3
  patreon: example4
  youtube: "@example"
  whatsapp: 1234567890
  medium: yourname
  reddit: yourname
  linkedin: example
  xing: yourname
  stackoverflow: "3943160/example"
  snapchat: example
  instagram: example
  spotify: yourname
  telephone: +14159998888
  steam: example
  twitch: yourname
  yelp: yourname
  telegram: yourname
  calendly: yourname
  mastodon: instance.url/@username
  bluesky: yourname
  ORCID: your ORCID ID
  google-scholar: your google scholar
  discord: "9Nu2KNWSwn"
  kaggle: yourname
  hackerrank: yourname
  gitlab: yourname
  itchio: yourname
  untappd: yourname

rss-description: test

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "MyWebsite.com"

title-on-all-pages: true

excerpt_length: 50

feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false

#exclude:
#  - CHANGELOG.md
#  - CNAME
#  - Gemfile
#  - Gemfile.lock
#  - LICENSE
#  - README.md
#  - screenshot.png
#  - docs/



description: "Official beta wiki of SCP: Foundation Cronicles"

#show_downloads: False


# remote_theme: pages-themes/hacker@v0.2.0


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme 


github:
  zip_url: http://example.com/download.zip
  tar_url: http://example.com/download.zip
