title: "SCP: FC Beta Wiki"
description: "Official beta wiki of SCP: Foundation Cronicles"
show_downloads: False
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
github:
  zip_url: http://example.com/download.zip
  tar_url: http://example.com/download.zip