title: test title
description: test descr.
show_downloads: True
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
github:
  zip_url: http://example.com/download.zip
  tar_gz_url: Null
  tar.gz_url: Null
